#Redis集群配置
spring:
  redis:
    cluster:
      nodes: 10.168.12.65:6500,10.168.12.65:6501,10.168.12.75:7500,10.168.12.75:7501,10.168.12.76:7600,10.168.12.76:7601
    timeout: 10000
    lettuce:
      pool:
        max-active: 500                         #连接池最大连接数
        max-idle: 100                            #连接池中的最大空闲连接
        max-wait: -1                            #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0
        timeout: 5000                                #连接超时时间（毫秒）